plugins {
    id 'java'
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'org.example.App'
}

dependencies {
    // Use JUnit test framework.
    testImplementation libs.junit

    // This dependency is used by the application.
    implementation libs.guava
    implementation platform("io.modelcontextprotocol.sdk:mcp-bom:0.12.1")
    implementation 'io.modelcontextprotocol.sdk:mcp'
}
