plugins {
    id 'java'
    id 'application'
}

ext {
    mcpVersion = "1.1.3"
    theMainClass = 'org.example.App'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = "${theMainClass}"
}

jar {
    manifest {
        attributes(
            'Main-Class': "${theMainClass}"
        )
    }
}

dependencies {
    implementation platform("io.modelcontextprotocol.sdk:mcp-bom:${mcpVersion}")
    implementation platform("org.apache.logging.log4j:log4j-bom:2.25.1")
    implementation "io.modelcontextprotocol.sdk:mcp"
    implementation "org.slf4j:slf4j-api:2.0.17"
    implementation "org.apache.logging.log4j:log4j-api"
    implementation "org.apache.logging.log4j:log4j-core"
    runtimeOnly "org.apache.logging.log4j:log4j-slf4j2-impl"
    testImplementation "io.modelcontextprotocol.sdk:mcp-test"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
